"""March C- memory BIST: a synthesizable controller and the testbench that runs it on a memory.

Standard library only, for the reason ``dft_scan.py`` is: the ``dft.mbist``
backend runs it as a step between Yosys (which reads the memory's ports) and
Icarus (which runs the controller against the memory). Nothing here runs a
tool or claims that one ran.

The memory is single port and synchronous: ``clk``, ``we``, ``addr``,
``wdata``, and a registered ``rdata`` (one cycle of read latency), over the
whole address space.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

CONTROLLER = "nirmaan_mbist"
TB_TOP = "nirmaan_mbist_tb"
#: March C-, element by element: (direction, operations).
MARCH_C_MINUS = (("any", "w0"), ("up", "r0,w1"), ("up", "r1,w0"), ("down", "r0,w1"), ("down", "r1,w0"),
                 ("any", "r0"))
PORTS = ("clk", "we", "addr", "wdata", "rdata")


class MemoryInterfaceError(ValueError):
    """The memory does not have the interface the controller drives."""


def memory_ports(netlist: dict, top: str) -> tuple[int, int]:
    """The address and data widths of ``top``, from Yosys's JSON; refuses any other interface."""
    module = netlist.get("modules", {}).get(top)
    if module is None:
        raise MemoryInterfaceError(f"no module {top!r} in the netlist")
    ports = module.get("ports", {})
    missing = [p for p in PORTS if p not in ports]
    if missing:
        raise MemoryInterfaceError(f"{top} lacks port(s) {', '.join(missing)}: the controller drives a single-port "
                           f"synchronous RAM ({', '.join(PORTS)})")
    width = {p: len(ports[p]["bits"]) for p in PORTS}
    wrong = [p for p in PORTS[:4] if ports[p]["direction"] != "input"] + (
        ["rdata"] if ports["rdata"]["direction"] != "output" else [])
    if wrong:
        raise MemoryInterfaceError(f"{top}: port(s) {', '.join(wrong)} have the wrong direction")
    if width["clk"] != 1 or width["we"] != 1 or width["wdata"] != width["rdata"] or width["addr"] > 16:
        raise MemoryInterfaceError(f"{top}: clk and we must be one bit, wdata and rdata the same width, addr at most 16 bits")
    return width["addr"], width["wdata"]


def controller(aw: int, dw: int) -> str:
    """The March C- controller for a memory of 2**aw words of dw bits, in synthesizable Verilog."""
    top = (1 << aw) - 1
    return f"""// March C- memory BIST controller: generated by nirmaan.integrations.dft_mbist.
// {{w0}} up(r0,w1) up(r1,w0) down(r0,w1) down(r1,w0) {{r0}}, solid backgrounds, over {top + 1} words of
// {dw} bits. A read takes two cycles: the address, then the compare of the registered data.
`timescale 1ns / 1ps
module {CONTROLLER} (
    input  wire          clk,
    input  wire          rst_n,
    input  wire          start,
    output wire          mem_we,
    output wire          mem_re,
    output wire [{aw - 1}:0]  mem_addr,
    output wire [{dw - 1}:0]  mem_wdata,
    input  wire [{dw - 1}:0]  mem_rdata,
    output wire          busy,
    output reg           done,
    output reg           fail,
    output reg  [2:0]    fail_element,
    output reg  [{aw - 1}:0]  fail_addr
);
    localparam [1:0] IDLE = 2'd0, RUN = 2'd1, CHECK = 2'd2, FINISHED = 2'd3;
    localparam [{aw - 1}:0] FIRST = {aw}'d0, LAST = {aw}'d{top};

    reg [1:0]      state;
    reg [2:0]      element;
    reg [{aw - 1}:0]    addr;
    reg            op;
    reg [{dw - 1}:0]    expected;

    // The March C- table: elements 1 to 4 read then write; element 0 only writes, element 5 only reads.
    wire two_ops = (element != 3'd0) && (element != 3'd5);
    wire is_read = (element == 3'd5) || (two_ops && !op);
    wire value = ((element == 3'd1) || (element == 3'd3)) ? op :
                 ((element == 3'd2) || (element == 3'd4)) ? !op : 1'b0;
    wire down = (element == 3'd3) || (element == 3'd4);
    wire last = addr == (down ? FIRST : LAST);
    wire [2:0] next_element = element + 3'd1;
    wire next_down = (next_element == 3'd3) || (next_element == 3'd4);
    wire advance = ((state == RUN) && !is_read) || (state == CHECK);

    assign mem_we = (state == RUN) && !is_read;
    assign mem_re = (state == RUN) && is_read;
    assign mem_addr = addr;
    assign mem_wdata = {{{dw}{{value}}}};
    assign busy = (state == RUN) || (state == CHECK);

    always @(posedge clk) begin
        if (!rst_n) begin
            state <= IDLE;
            element <= 3'd0;
            addr <= FIRST;
            op <= 1'b0;
            expected <= {dw}'d0;
            done <= 1'b0;
            fail <= 1'b0;
            fail_element <= 3'd0;
            fail_addr <= FIRST;
        end else begin
            case (state)
                IDLE: begin
                    if (start) begin
                        state <= RUN;
                        element <= 3'd0;
                        addr <= FIRST;
                        op <= 1'b0;
                        done <= 1'b0;
                        fail <= 1'b0;
                    end
                end
                RUN: begin
                    if (is_read) begin
                        expected <= {{{dw}{{value}}}};
                        state <= CHECK;
                    end
                end
                CHECK: begin
                    if (mem_rdata != expected && !fail) begin
                        fail <= 1'b1;
                        fail_element <= element;
                        fail_addr <= addr;
                    end
                end
                default: begin
                end
            endcase
            if (advance) begin
                state <= RUN;
                if (two_ops && !op) begin
                    op <= 1'b1;
                end else begin
                    op <= 1'b0;
                    if (!last) begin
                        addr <= down ? addr - {aw}'d1 : addr + {aw}'d1;
                    end else if (element == 3'd5) begin
                        state <= FINISHED;
                        done <= 1'b1;
                    end else begin
                        element <= next_element;
                        addr <= next_down ? LAST : FIRST;
                    end
                end
            end
        end
    end
endmodule
"""


def testbench(top: str, aw: int, dw: int) -> str:
    """Connect the controller to memory ``top``, run March C- once, and count what it did."""
    words = 1 << aw
    limit = 20 * words + 100
    return f"""`timescale 1ns / 1ps
// March C- on {top}: generated by nirmaan.integrations.dft_mbist.
module {TB_TOP};
  reg clk, rst_n, start;
  wire we, re, busy, done, fail;
  wire [{aw - 1}:0] addr, fail_addr;
  wire [{dw - 1}:0] wdata, rdata;
  wire [2:0] fail_element;
  reg checking;
  integer reads, writes, cycles, x_reads;

  {top} mem (.clk(clk), .we(we), .addr(addr), .wdata(wdata), .rdata(rdata));
  {CONTROLLER} bist (.clk(clk), .rst_n(rst_n), .start(start), .mem_we(we), .mem_re(re), .mem_addr(addr),
                     .mem_wdata(wdata), .mem_rdata(rdata), .busy(busy), .done(done), .fail(fail),
                     .fail_element(fail_element), .fail_addr(fail_addr));

  always #5 clk = ~clk;

  // Count every operation the controller makes, independently of its own verdict.
  always @(posedge clk) begin
    if (checking && ^rdata === 1'bx)
      x_reads = x_reads + 1;
    checking <= re;
    if (busy) begin
      cycles = cycles + 1;
      if (we)
        writes = writes + 1;
      if (re)
        reads = reads + 1;
    end
  end

  initial begin
    clk = 1'b0;
    rst_n = 1'b0;
    start = 1'b0;
    checking = 1'b0;
    reads = 0;
    writes = 0;
    cycles = 0;
    x_reads = 0;
    repeat (2) @(negedge clk);
    rst_n = 1'b1;
    @(negedge clk);
    start = 1'b1;
    @(negedge clk);
    start = 1'b0;
    while (!done && cycles < {limit})
      @(negedge clk);
    $write("DFT-MBIST: march C-, words {words}, width {dw}, reads %0d, writes %0d, cycles %0d, ", reads, writes,
           cycles);
    $display("x reads %0d, done %0d, fail %0d, element %0d, address %0d", x_reads, done, fail, fail_element,
             fail_addr);
    $finish;
  end
endmodule
"""


def main(argv: list[str]) -> int:
    try:
        if argv[:1] == ["generate"] and len(argv) == 5:
            _, ports_json, controller_v, tb_v, top = argv
            aw, dw = memory_ports(json.loads(Path(ports_json).read_text(encoding="utf-8")), top)
            Path(controller_v).write_text(controller(aw, dw), encoding="utf-8")
            Path(tb_v).write_text(testbench(top, aw, dw), encoding="utf-8")
            print(f"DFT-MBIST-GEN: March C- for {top}, {1 << aw} words of {dw} bits")
            return 0
    except (MemoryInterfaceError, OSError, KeyError, json.JSONDecodeError) as exc:
        print(f"DFT-ERROR: {exc}")
        return 1
    print("usage: dft_mbist.py generate PORTS.json CONTROLLER.v TB.v TOP")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
