"""Generate and check the counts that the roadmap and the landing page state.

Structural counts (units, roles, skills, workflows, principles, tools by status,
knowledge packs) come from the code and are checked on every PR against the
generated block in docs/ROADMAP.md. The test count is a release snapshot: it is
collected only by --release and kept, with the version, in site/stats.json,
which is also where the landing page gets every number. See docs/STATUS_DOCS.md.

    python scripts/status.py            print the counts and any drift
    python scripts/status.py --check    exit 1 if the roadmap or the site disagree
    python scripts/status.py --write    rewrite the roadmap block
    python scripts/status.py --release  collect tests; write stats.json, the site, the block

Run with PYTHONPATH=src or an installed package.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROADMAP = ROOT / "docs" / "ROADMAP.md"
STATS = ROOT / "site" / "stats.json"
SITE = ROOT / "site" / "index.html"

BEGIN = "<!-- status:begin (generated by scripts/status.py --write; do not edit by hand) -->"
END = "<!-- status:end -->"

# Every structural count, with the label the roadmap block gives it.
STRUCTURAL = {
    "units": "Organizational units",
    "roles": "Derived roles",
    "skills": "Skills",
    "workflows": "Workflows",
    "principles": "Constitution principles",
    "tools_available": "Tools `AVAILABLE`",
    "tools_contract_only": "Tools `CONTRACT_ONLY`",
    "knowledge_packs": "Verification knowledge packs",
}

TILE = re.compile(
    r'(<span class="stat__num" data-stat="(?P<key>\w+)" data-count=")(?P<count>\d+)(">)(?P<shown>\d+)(<)'
)


def structural_counts() -> dict[str, int]:
    from nirmaan.company import build_organization
    from nirmaan.models.org import ToolStatus
    from veritriage.knowledge.registry import available_packs

    org = build_organization()
    stats = org.stats()
    tools = list(org.tools.values())
    return {
        "units": stats["units"],
        "roles": stats["roles"],
        "skills": stats["skills"],
        "workflows": stats["workflows"],
        "principles": stats["principles"],
        "tools_available": sum(t.status is ToolStatus.AVAILABLE for t in tools),
        "tools_contract_only": sum(t.status is ToolStatus.CONTRACT_ONLY for t in tools),
        "knowledge_packs": len(available_packs()),
    }


def collect_test_count() -> int:
    """Every test pytest collects: the suite CI runs, PD-only and SDK tests included."""
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "-o", "addopts=", "-p", "no:cacheprovider"],
        cwd=ROOT, capture_output=True, text=True, check=False,
    )
    match = re.search(r"^(\d+) tests? collected", result.stdout, re.M)
    if not match:
        raise SystemExit(f"could not count tests:\n{result.stdout[-2000:]}{result.stderr[-2000:]}")
    return int(match.group(1))


def version() -> str:
    return tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]["version"]


def load_stats() -> dict:
    return json.loads(STATS.read_text(encoding="utf-8"))


# --- The roadmap block ---------------------------------------------------------------


def roadmap_block(counts: dict[str, int], stats: dict) -> str:
    rows = [f"| {label} | {counts[key]} | `{key}`, every PR |" for key, label in STRUCTURAL.items()]
    rows.append(f"| Tests collected | {stats['tests']} | `tests`, at release (v{stats['version']}) |")
    return "\n".join([BEGIN, "| Count | Value | Key, checked |", "|---|---|---|", *rows, END])


def _current_block(text: str) -> str:
    start, end = text.find(BEGIN), text.find(END)
    if start < 0 or end < start:
        raise SystemExit(f"{ROADMAP.relative_to(ROOT)}: no status block between the markers")
    return text[start:end + len(END)]


def check_roadmap() -> list[str]:
    counts, stats = structural_counts(), load_stats()
    shown = _current_block(ROADMAP.read_text(encoding="utf-8"))
    problems = []
    for line_now, line_shown in zip(roadmap_block(counts, stats).splitlines(), shown.splitlines()):
        if line_now != line_shown:
            key = re.search(r"`(\w+)`, ", line_now)
            problems.append(f"docs/ROADMAP.md says {line_shown!r}, the code says {line_now!r}"
                            f" ({key.group(1) if key else 'block'}): run scripts/status.py --write")
    if not problems and len(shown.splitlines()) != len(roadmap_block(counts, stats).splitlines()):
        problems.append("docs/ROADMAP.md status block has the wrong rows: run scripts/status.py --write")
    return problems


def write_roadmap() -> None:
    text = ROADMAP.read_text(encoding="utf-8")
    ROADMAP.write_text(text.replace(_current_block(text), roadmap_block(structural_counts(), load_stats())),
                       encoding="utf-8")


# --- The landing page ----------------------------------------------------------------


def check_site() -> list[str]:
    """The page's tiles against stats.json only: the code is not consulted."""
    stats, html = load_stats(), SITE.read_text(encoding="utf-8")
    tiles = list(TILE.finditer(html))
    problems = [] if tiles else ["site/index.html has no data-stat tiles"]
    for tile in tiles:
        key = tile["key"]
        if key not in stats:
            problems.append(f"site tile {key!r} is not in site/stats.json")
        elif not int(tile["count"]) == int(tile["shown"]) == stats[key]:
            problems.append(f"site tile {key!r} shows {tile['shown']} (data-count {tile['count']}),"
                            f" site/stats.json says {stats[key]}: run scripts/status.py --release")
    return problems


def write_site(stats: dict) -> None:
    html = SITE.read_text(encoding="utf-8")
    html = TILE.sub(lambda m: f"{m[1]}{stats[m['key']]}{m[4]}{stats[m['key']]}{m[6]}", html)
    SITE.write_text(html, encoding="utf-8")


def release() -> dict:
    stats = {"version": version(), **structural_counts(), "tests": collect_test_count()}
    STATS.write_text(json.dumps(stats, indent=2) + "\n", encoding="utf-8")
    write_site(stats)
    write_roadmap()
    return stats


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="exit 1 on drift")
    mode.add_argument("--write", action="store_true", help="rewrite the roadmap block")
    mode.add_argument("--release", action="store_true", help="snapshot every count, tests included")
    args = parser.parse_args(argv)

    if args.release:
        print(json.dumps(release(), indent=2))
        return 0
    if args.write:
        write_roadmap()
        return 0
    for key, value in structural_counts().items():
        print(f"{key:22} {value}")
    stats = load_stats()
    print(f"{'tests':22} {stats['tests']} (at v{stats['version']}, from site/stats.json)")
    problems = check_roadmap() + check_site()
    for problem in problems:
        print(problem, file=sys.stderr)
    return 1 if problems and args.check else 0


if __name__ == "__main__":
    sys.exit(main())
